services:
  redis:
    image: redis:7.4.1-bookworm
    restart: unless-stopped
    ports:
      - '6379:6379'
#
#
#

#  db-backup:
#    # https://github.com/weather-blade/weather-db-backup
#    image: ghcr.io/weather-blade/weather-db-backup:latest
#    restart: unless-stopped
#    depends_on:
#      - db
#    environment:
#      DATABASE_URL: ${DATABASE_URL}
#      GDRIVE_FOLDER_ID: ${GDRIVE_FOLDER_ID}
#    volumes:
#      - ./SA_key.json:/app/SA_key.json:ro

#  server:
#    build: .
#    restart: unless-stopped
#    ports:
#      - 8080:8080
#      - 5555:5555 # prisma studio
#    depends_on:
#      - redis
#      - db
#    volumes:
#      - ./:/app
#    command: pnpm run dev
#    environment:
#      PORT: ${PORT}
#      API_PASSWORD: ${API_PASSWORD}
#      DATABASE_URL: ${DATABASE_URL}
#      VAPID_PRIVATE_KEY: ${VAPID_PRIVATE_KEY}
#      VAPID_PUBLIC_KEY: ${VAPID_PUBLIC_KEY}

