services:
  redis:
    image: redis:7.2.2-bookworm
    restart: unless-stopped

  db:
    image: postgres:15.2
    restart: unless-stopped
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

  db-backup:
    # https://github.com/weather-blade/weather-db-backup
    image: ghcr.io/weather-blade/weather-db-backup:latest
    restart: unless-stopped
    depends_on:
      - db
    environment:
      DATABASE_URL: ${DATABASE_URL}
      GDRIVE_FOLDER_ID: ${GDRIVE_FOLDER_ID}
    volumes:
      - ./SA_key.json:/app/SA_key.json:ro

  notifications:
    # https://github.com/weather-blade/weather-notifications
    image: ghcr.io/weather-blade/weather-notifications:latest
    restart: unless-stopped
    depends_on:
      - db
    environment:
      DATABASE_URL: ${DATABASE_URL}
      VAPID_PRIVATE_KEY: ${VAPID_PRIVATE_KEY}
      VAPID_PUBLIC_KEY: ${VAPID_PUBLIC_KEY}

  server:
    image: ghcr.io/weather-blade/weather-server:latest
    restart: unless-stopped
    depends_on:
      - redis
      - db
    environment:
      PORT: ${PORT}
      API_PASSWORD: ${API_PASSWORD}
      DATABASE_URL: ${DATABASE_URL}
      VAPID_PRIVATE_KEY: ${VAPID_PRIVATE_KEY}
      VAPID_PUBLIC_KEY: ${VAPID_PUBLIC_KEY}
    networks:
      - 'nginx_proxy_net'
      - 'default'

volumes:
  db-data:

networks:
  nginx_proxy_net:
    external: true
