FROM debian:bookworm-slim

RUN apt-get update && apt-get upgrade -y

RUN apt-get install curl -y
RUN curl -L https://fly.io/install.sh | FLYCTL_INSTALL=/usr/local sh

RUN mkdir /app
WORKDIR /app

COPY . .

# run `flyctl status` and `flyctl auth token` to get these
CMD flyctl deploy --app $FLY_APP_NAME --access-token $FLY_API_ACCESS_TOKEN
