services:
  redis:
    image: redis:7.2.2-bookworm
    restart: unless-stopped

  db:
    image: postgres:15.2
    restart: unless-stopped
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: weather_station_dev

  db-backup:
    # https://github.com/weather-blade/weather-db-backup
    image: ghcr.io/weather-blade/weather-db-backup:latest
    restart: unless-stopped
    depends_on:
      - db
    env_file:
      - .env
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - GDRIVE_FOLDER_ID=${GDRIVE_FOLDER_ID}
    volumes:
      - ./SA_key.json:/app/SA_key.json:ro

  notifications:
    # https://github.com/weather-blade/weather-notifications
    image: ghcr.io/weather-blade/weather-notifications:latest
    restart: unless-stopped
    depends_on:
      - db
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - VAPID_PRIVATE_KEY=${VAPID_PRIVATE_KEY}
      - VAPID_PUBLIC_KEY=${VAPID_PUBLIC_KEY}
    env_file:
      - .env

  server:
    build: .
    restart: unless-stopped
    ports:
      - 8080:8080
      - 5555:5555 # prisma studio
    depends_on:
      - redis
      - db
    env_file:
      - .env
    environment:
      - VIRTUAL_HOST=weatherapi.bladesheng.com,www.weatherapi.bladesheng.com
      - LETSENCRYPT_HOST=weatherapi.bladesheng.com,www.weatherapi.bladesheng.com
      - VIRTUAL_PORT=8080

volumes:
  db-data:
